repos:
  - repo: local
    hooks:
      - id: ruff-format
        language: python
        name: ruff-format
        pass_filenames: false
        language_version: python3.10
        entry: poetry run ruff format fastapi_async_safe tests

  - repo: local
    hooks:
      - id: ruff
        language: python
        name: ruff
        pass_filenames: false
        language_version: python3.10
        entry: poetry run ruff --fix --exit-non-zero-on-fix --show-fixes fastapi_async_safe tests

  - repo: local
    hooks:
      - id: mypy
        language: python
        name: mypy
        pass_filenames: false
        entry: poetry run mypy fastapi_async_safe --show-error-codes
